name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "446013bd-b7b4-41c9-bcee-3630e719c593"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "2b2c707d37a44b13bdae3c2e77cd790c"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
